[platformio]
default_envs = giga_r1_m7_spe_expert1k

[env:giga_r1_m7_spe_expert1k]
platform = ststm32@19.6.0
board = giga_r1_m7
framework = arduino
upload_port = COM27
monitor_port = COM27
monitor_speed = 115200
lib_ldf_mode = chain
lib_compat_mode = off
extra_scripts =
    pre:tools/patch_arduino_h7_video.py
build_src_filter =
    +<*>
    -<wifi_firmware_updater.cpp>
lib_deps =
    lvgl/lvgl @ ^9.5.0
    arduino-libraries/Arduino_GigaDisplay_GFX @ ^1.1.0
    arduino-libraries/Arduino_GigaDisplayTouch @ ^1.1.0
build_unflags =
    -O0
    -O1
    -O2
    -O3
    -Og
build_flags =
    -I include
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -D LV_CONF_PATH=\"lv_conf.h\"
    -D SPE_MANUAL_LVGL_DISPLAY
    -D SPE_ENABLE_WIFI_SETUP=1
    -D SPE_ENABLE_WEB_SERVER=1

[env:giga_r1_m7_wifi_firmware_updater]
platform = ststm32@19.6.0
board = giga_r1_m7
framework = arduino
upload_port = COM27
monitor_port = COM27
monitor_speed = 115200
build_src_filter =
    -<*>
    +<wifi_firmware_updater.cpp>
extra_scripts =
    pre:tools/add_wifi_firmware_include.py
