// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SPE_Expert1K

#ifndef UI_BOOTSCREEN_H
#define UI_BOOTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_bootScreen
extern void ui_bootScreen_screen_init(void);
extern void ui_bootScreen_screen_destroy(void);
extern lv_obj_t * ui_bootScreen;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_startupBar;
extern lv_obj_t * ui_startupMessage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

