// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SPE_Expert1K

#ifndef _UI_COMP_SPE_H
#define _UI_COMP_SPE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT spe
#define UI_COMP_SPE_SPE 0
#define _UI_COMP_SPE_NUM 1
lv_obj_t * ui_spe_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
