// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SPE_Expert1K

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainScreen
extern void ui_mainScreen_screen_init(void);
extern void ui_mainScreen_screen_destroy(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_receive;
extern lv_obj_t * ui_status;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_ampStatus;
extern lv_obj_t * ui_inLabel;
extern lv_obj_t * ui_bandLabel;
extern lv_obj_t * ui_antLabel;
extern lv_obj_t * ui_catLabel;
extern lv_obj_t * ui_outLabel;
extern lv_obj_t * ui_swrLabel;
extern lv_obj_t * ui_tempLabel;
extern lv_obj_t * ui_leftButtons;
extern void ui_event_buttonLowerL(lv_event_t * e);
extern lv_obj_t * ui_buttonLowerL;
extern lv_obj_t * ui_labelLowerL;
extern void ui_event_buttonHigherL(lv_event_t * e);
extern lv_obj_t * ui_buttonHigherL;
extern lv_obj_t * ui_laberlHigherL;
extern void ui_event_buttonLowerC(lv_event_t * e);
extern lv_obj_t * ui_buttonLowerC;
extern lv_obj_t * ui_labelLowerC;
extern void ui_event_buttonHigherC(lv_event_t * e);
extern lv_obj_t * ui_buttonHigherC;
extern lv_obj_t * ui_labelHigherC;
extern void ui_event_buttonTune(lv_event_t * e);
extern lv_obj_t * ui_buttonTune;
extern lv_obj_t * ui_labelTune;
extern lv_obj_t * ui_rightButtons;
extern void ui_event_buttonOff(lv_event_t * e);
extern lv_obj_t * ui_buttonOff;
extern lv_obj_t * ui_labelOff;
extern void ui_event_buttonOn(lv_event_t * e);
extern lv_obj_t * ui_buttonOn;
extern lv_obj_t * ui_labelOn;
extern void ui_event_buttonPower(lv_event_t * e);
extern lv_obj_t * ui_buttonPower;
extern lv_obj_t * ui_labelPower;
extern void ui_event_buttonDisplay(lv_event_t * e);
extern lv_obj_t * ui_buttonDisplay;
extern lv_obj_t * ui_labelDisplay;
extern void ui_event_buttonOperate(lv_event_t * e);
extern lv_obj_t * ui_buttonOperate;
extern lv_obj_t * ui_labelOperate;
extern lv_obj_t * ui_mainButtons;
extern void ui_event_buttonInput(lv_event_t * e);
extern lv_obj_t * ui_buttonInput;
extern lv_obj_t * ui_labelInput;
extern void ui_event_buttonBandDown(lv_event_t * e);
extern lv_obj_t * ui_buttonBandDown;
extern lv_obj_t * ui_labelBandDown;
extern void ui_event_buttonBandUp(lv_event_t * e);
extern lv_obj_t * ui_buttonBandUp;
extern lv_obj_t * ui_labelBandUp;
extern void ui_event_buttonAnt(lv_event_t * e);
extern lv_obj_t * ui_buttonAnt;
extern lv_obj_t * ui_labelAnt;
extern void ui_event_buttonLeftUp(lv_event_t * e);
extern lv_obj_t * ui_buttonLeftUp;
extern lv_obj_t * ui_labelLeftUp;
extern void ui_event_buttonRightDown(lv_event_t * e);
extern lv_obj_t * ui_buttonRightDown;
extern lv_obj_t * ui_labelRightDown;
extern void ui_event_buttonCat(lv_event_t * e);
extern lv_obj_t * ui_buttonCat;
extern lv_obj_t * ui_labelCat;
extern void ui_event_buttonSet(lv_event_t * e);
extern lv_obj_t * ui_buttonSet;
extern lv_obj_t * ui_labelSet;
extern lv_obj_t * ui_manualTune;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_manualTuneuH;
extern lv_obj_t * ui_manualTunepF;
extern lv_obj_t * ui_manualTuneFreq;
extern lv_obj_t * ui_manualTuneSubBand;
extern lv_obj_t * ui_manualTuneuHLabel;
extern lv_obj_t * ui_manualTunepFLabel;
extern lv_obj_t * ui_transmit;
extern lv_obj_t * ui_status1;
extern lv_obj_t * ui_vPA;
extern lv_obj_t * ui_powerBar;
extern lv_obj_t * ui_pep;
extern lv_obj_t * ui_vPALabel;
extern lv_obj_t * ui_vBar;
extern lv_obj_t * ui_powerLabel;
extern lv_obj_t * ui_alarmHistory;
extern lv_obj_t * ui_status2;
extern lv_obj_t * ui_alarmLine1;
extern lv_obj_t * ui_alarmLine2;
extern lv_obj_t * ui_alarmLine3;
extern lv_obj_t * ui_alarmLine4;
extern lv_obj_t * ui_alarmControl;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_systemMessage;
extern lv_obj_t * ui_status4;
extern lv_obj_t * ui_systemMessageText;
extern lv_obj_t * ui_warningScreen;
extern lv_obj_t * ui_status3;
extern lv_obj_t * ui_warningText;
extern lv_obj_t * ui_warningControl;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_setupAntOptions;
extern lv_obj_t * ui_setupAntHeaderText;
extern lv_obj_t * ui_setupAntFooterText;
extern lv_obj_t * ui_setupAntBottomLabel;
extern lv_obj_t * ui_setupAntContainer1;
extern lv_obj_t * ui_setupAntContainer2;
extern lv_obj_t * ui_setupAntContainer3;
extern lv_obj_t * ui_setupOptions;
extern lv_obj_t * ui_setupHeaderText;
extern lv_obj_t * ui_setupFooterText;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_setupCatOptions;
extern lv_obj_t * ui_setupCatHeaderText;
extern lv_obj_t * ui_setupCatFooterText;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_setupYaesuOptions;
extern lv_obj_t * ui_setupYaesuHeaderText;
extern lv_obj_t * ui_setupYaesuFooterText;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_setupIcomOptions;
extern lv_obj_t * ui_setupIcomHeaderText;
extern lv_obj_t * ui_setupIcomFooterText;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_setupTenTecOptions;
extern lv_obj_t * ui_setupTenTecHeaderText;
extern lv_obj_t * ui_setupTenTecFooterText;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_setupBaudRateOptions;
extern lv_obj_t * ui_setupBaudRateHeaderText;
extern lv_obj_t * ui_setupBaudRateFooterText;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_setupBaudRateContainer1;
extern lv_obj_t * ui_seutpBaudCatType;
extern lv_obj_t * ui_setupBaudCatModel;
extern lv_obj_t * ui_setupBaudRateContainer2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_backlight;
extern lv_obj_t * ui_setupHeaderText1;
extern lv_obj_t * ui_setupFooterText1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_backlightLevel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

